server:
  port: 8082
  

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microServices_rating_services?createDatabaseIfNotExist=TRUE
    username: root
    password: sayan
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
      
  config:
    import: "optional:configserver: http://localhost:8085"
    
#
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defualt: http://localhost:8761/euraka